-- ------------------------------------------------------------
-- Personal CMS - Database Schema
-- Import this file into MySQL/phpMyAdmin before running the app.
-- ------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS cms_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cms_db;

-- ----------------------------
-- Table: users
-- ----------------------------
CREATE TABLE IF NOT EXISTS users (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL UNIQUE,
    email      VARCHAR(100) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    role       ENUM('admin', 'user') NOT NULL DEFAULT 'user',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ----------------------------
-- Table: posts
-- ----------------------------
CREATE TABLE IF NOT EXISTS posts (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    user_id    INT NULL,
    title      VARCHAR(150) NOT NULL,
    content    TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- ----------------------------
-- Sample data (optional)
-- NOTE: No admin user is seeded here because password hashes must be
-- generated by PHP's password_hash() at runtime. After importing this
-- schema, either:
--   1) Visit auth/register.php in your browser to create your first
--      account (then optionally promote it to role='admin' in phpMyAdmin), or
--   2) Run setup/create_admin.php once from your browser to create a
--      ready-made admin account, then delete that file for security.
-- ----------------------------

INSERT INTO posts (user_id, title, content) VALUES
(NULL, 'Welcome to my Personal CMS', 'This is the first post created from the CMS dashboard. Feel free to edit or delete it, or create new posts of your own!'),
(NULL, 'Getting Started with PHP & MySQL', 'This site is built with plain PHP, PDO prepared statements, and Bootstrap 5. Explore the dashboard to see the full CRUD workflow in action.'),
(NULL, 'Why I Built This Project', 'A lightweight, secure, and responsive content management system for managing simple blog-style posts, complete with authentication and an admin dashboard.');
