-- ------------------------------------------------------
-- Simple CMS - Database Schema
-- Import this into phpMyAdmin / MySQL before running the app.
-- ------------------------------------------------------

CREATE DATABASE IF NOT EXISTS cms_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cms_db;

-- Users table: stores accounts for both admins and normal users
CREATE TABLE IF NOT EXISTS users (
    id       INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,               -- hashed with password_hash()
    role     ENUM('admin', 'user') NOT NULL DEFAULT 'user',
    status   ENUM('active', 'blocked') NOT NULL DEFAULT 'active'
) ENGINE=InnoDB;

-- Subjects table: categories that files belong to (e.g. "Programming")
CREATE TABLE IF NOT EXISTS subjects (
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB;

-- Files table: files uploaded under a subject
CREATE TABLE IF NOT EXISTS files (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    subject_id INT NOT NULL,
    filename   VARCHAR(255) NOT NULL,             -- name of the file as stored on disk
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ------------------------------------------------------
-- NOTE: We do NOT insert a default admin here, because password
-- hashes must be generated by PHP's password_hash() function, not
-- typed by hand into SQL. After importing this file, open
-- setup/create_admin.php in your browser once to create your first
-- admin account, then delete that file for security.
-- ------------------------------------------------------
