-- ------------------------------------------------------------
-- Personal Portfolio CMS - Database Schema
-- Import this file into MySQL/phpMyAdmin before running the app.
-- (Note: config/db.php also creates these tables automatically on
-- first run, so importing this file manually is optional.)
-- ------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS cms_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cms_db;

-- ----------------------------
-- Table: users
-- ----------------------------
CREATE TABLE IF NOT EXISTS users (
    id             INT AUTO_INCREMENT PRIMARY KEY,
    username       VARCHAR(50)  NOT NULL UNIQUE,
    email          VARCHAR(100) NULL,
    password       VARCHAR(255) NOT NULL,
    role           ENUM('admin','user') NOT NULL DEFAULT 'user',
    status         ENUM('active','blocked') NOT NULL DEFAULT 'active',
    profile_image  VARCHAR(255) NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ----------------------------
-- Table: portfolio
-- ----------------------------
CREATE TABLE IF NOT EXISTS portfolio (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    title         VARCHAR(150),
    description   TEXT,
    image         VARCHAR(255),
    category      ENUM('Web App','Study Material') NOT NULL DEFAULT 'Web App',
    link          VARCHAR(255) NULL,
    preview_image VARCHAR(255) NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ----------------------------
-- Table: contact_messages
-- ----------------------------
CREATE TABLE IF NOT EXISTS contact_messages (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100),
    email      VARCHAR(100),
    message    TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ----------------------------
-- Table: cms_pages (editable Home / About / Portfolio content)
-- ----------------------------
CREATE TABLE IF NOT EXISTS cms_pages (
    id        INT AUTO_INCREMENT PRIMARY KEY,
    page_name VARCHAR(50) NOT NULL UNIQUE,
    content   TEXT
) ENGINE=InnoDB;

INSERT IGNORE INTO cms_pages (page_name, content) VALUES
('home', 'Welcome to my personal portfolio website.'),
('about', 'I am Adrian Rovic A. Corrales, a 2nd Year Student from FEU Institute of Technology, pursuing a degree in BSITCST.'),
('portfolio', 'A showcase of work and projects.');

-- ----------------------------
-- Table: documentation (admin-only User Manual PDF)
-- ----------------------------
CREATE TABLE IF NOT EXISTS documentation (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    file_name    VARCHAR(255),
    file_path    VARCHAR(255),
    uploaded_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ----------------------------
-- NOTE: No admin user is seeded here because password hashes must be
-- generated by PHP's password_hash() at runtime. Simply visiting the
-- site for the first time will auto-create a default admin account
-- (username: admin, password: Admin123!) - see config/db.php.
-- ----------------------------
